# Generated by Django 5.1.4 on 2025-01-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['cedula'], name='UQ__EMPLEADO__06BB84481363A4AA'),
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='EMPLEADOS',
        ),
    ]
